command = "cdl/target/${TARGET:-debug}/api"
start-delay = "2s"
# start-after = ["another.toml", "second.toml"]
stdout = "logs/api.log"
stderr = "logs/api.log"
user = "$USER"
working-directory = "."

[restart]
strategy = "never"
backoff = "0s"
attempts = 0

[failure]
successful-exit-code = [ 0, 1, 255]
strategy = "ignore"

[environment]
keep-env = false
#re-export = [ "PATH", "DB_PASS"]

[environment.additional]
CDL_CONFIG                  = "cdl/.cdl"

[termination]
signal = "TERM"
wait = "2s"
#die-if-failed  = [ "db.toml"]
